### ISSUE TITLE
Criar LDE

### ISSUE THREAD

**Issue by VicttorSM** [VicttorSM/DataStructures#1]
### Deve conter no mínimo as seguintes funções:
- ```boolean insere(T valor)```
   - de preferencia inserir valores ordenadamente
   - recebe um valor do tipo T por parâmetro
   - retorna ```true``` se conseguiu inserir ou ```false``` caso contrario
- ```No<T> busca(T valor)```
   - recebe um valor do tipo T por parâmetro
   - retorna o No caso o ache ou ```null``` caso contrario
- ```boolean remove(T valor)```
   - recebe um valor do tipo T por parâmetro
   - retorna ```true``` se conseguiu remover ou ```false``` caso contrario

### Obs: Se não conseguir usar o tipo genérico T, pode usar String ou int primeiro e commitar

**Comment by WillGB** [comment]
Done
